# Generated by Django 4.0.3 on 2022-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
