# Generated by Django 4.0.3 on 2022-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_decoration_alter_gift_gift_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
