# Generated by Django 4.0.3 on 2022-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
